### ISSUE TITLE
where is  'bubble' ?

### ISSUE THREAD

**Issue by le0zh** [rusfearuth/react-native-9patch-image#1]
hi, as your demo:

```
 source={{ 'uri': 'bubble' }}
```

where should i put my nine patch image? such as 'bubble' ?

**Comment by rusfearuth** [comment]
@le0zh Hi! Sorry for bad documentation (

The bubble is png image(s) which located into `ios/{your project folder}/Images.xcassets` folder and `android/app/src/main/res/drawable-(mdpi/hdpi/xhdpi and etc.)` folders.

Bubble image for iOS should be as Insets image for Android it should be 9patch.

**Comment by le0zh** [comment]
@rusfearuth  I see, thank you very much.

**Comment by Kishanjvaghela** [comment]
@rusfearuth Thanks a lot
